CREATE DATABASE pasantesdo;


CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL, 
    name VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
);

ALTER TABLE users ADD COLUMN phone VARCHAR NOT NULL;


CREATE TABLE IF NOT EXISTS role (
 id SERIAL PRIMARY KEY NOT NULL, 
 name VARCHAR NOT NULL,
 description VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role (
 id SERIAL PRIMARY KEY NOT NULL, 
 user_id INTEGER NOT NULL,
 role_id INTEGER NOT NULL,

 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (role_id) REFERENCES role(id)
);